### ISSUE TITLE
rules_sass is broken on Bazel CI by Dart Sass upgrade

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_sass#115]
https://buildkite.com/bazel/rules-sass/builds/544
```
(04:02:10) ERROR: /workdir/examples/hello_world/BUILD:24:1: SassCompiler examples/hello_world/main-no-sourcemap.css failed (Exit 1)
Compilation failed TypeError: sass.run_ is not a function
    at /workdir/sass/sass_wrapper.js:20:30
    at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/io_bazel_rules_sass/bazel-out/host/bin/sass/sass.sh.runfiles/build_bazel_rules_sass_deps/node_modules/@bazel/worker/index.js:166:53
    at Generator.next (<anonymous>)
    at fulfilled (/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/io_bazel_rules_sass/bazel-out/host/bin/sass/sass.sh.runfiles/build_bazel_rules_sass_deps/node_modules/@bazel/worker/index.js:3:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Caused by https://github.com/bazelbuild/rules_sass/commit/7d8ec2207120580a8a1d3960bdea3968ace5038f

/cc @jelbourn Can you help fixing this?
